# 服务端口
server:
  port: 8999
spring:
  # 服务名称
  application:
    name: seckill
  # 环境设置
  profiles:
    active: dev
  # Mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xzx-hospital-one?serverTimezone=GMT%2B8
    username: root
    password: xzx123
  # Json格式化时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Redis
  redis:
    timeout: 10000ms
    host: localhost
    port: 6379
    database: 2
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

# mybatis-plus日志
mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/xml/*.xml
